name: env_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - folium
  - bottleneck
  - xgboost
  - pip
  - pip:
    - streamlit
    - streamlit-folium
    - openai==0.27.0
    - python-dotenv